### PR TITLE
Introduce MergeTree with reader and writer

### PR DESCRIPTION
**Pull request by JingsongLi**

### CODE REVIEW

**Comment by JingsongLi** [comment]
Some tests have not finished, please wait.

**Comment by JingsongLi** [comment]
This is ready for reviewing. @tsreaper

**Review by tsreaper — COMMENTED** [review]
Looks good to me. Just some minor comments.

**Comment by tsreaper** [comment]
Also why moving `RecordReaderIterator` from test to src? It is not used in production code.

**Comment by JingsongLi** [comment]
> RecordReaderIterator

We must convert `RecordReader` to a `Iterator` for `SstFile.write`.

**Review by tsreaper — APPROVED** [review]

**Pull request merged**
